Args = --enable-url-protocols=http,https \
       --report-unsupported-elements-at-runtime \
       --no-fallback \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       -H:+JNI \
       -H:+IncludeAllLocales \
       -H:+UnlockExperimentalVMOptions \
       -H:+AllowIncompleteClasspath