Args = --enable-url-protocols=http,https \
       --report-unsupported-elements-at-runtime \
       --no-fallback \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets \
       -H:+JNI \
       -H:+IncludeAllLocales \
       -H:+UnlockExperimentalVMOptions \
       -H:+AllowIncompleteClasspath \
       -H:ReflectionConfigurationResources=META-INF/native-image/NexylEngine/reflect-config.json \
       -H:JNIConfigurationResources=META-INF/native-image/NexylEngine/jni-config.json \
       -H:ResourceConfigurationResources=META-INF/native-image/NexylEngine/resource-config.json \
       -H:DynamicProxyConfigurationResources=META-INF/native-image/NexylEngine/proxy-config.json \
       -H:SerializationConfigurationResources=META-INF/native-image/NexylEngine/serialization-config.json